package com.personInfo.bean;

import java.util.Date;

public class VipPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.config_id
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Long configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.user_id
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.is_view
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Byte isView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.likes
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.album_count
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Integer albumCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.diary_pic_count
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Integer diaryPicCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.is_back
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Byte isBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.update_time
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_disable_date_vip_permissions.update_admin
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    private Integer updateAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.config_id
     *
     * @return the value of tb_disable_date_vip_permissions.config_id
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.config_id
     *
     * @param configId the value for tb_disable_date_vip_permissions.config_id
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.user_id
     *
     * @return the value of tb_disable_date_vip_permissions.user_id
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.user_id
     *
     * @param userId the value for tb_disable_date_vip_permissions.user_id
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.is_view
     *
     * @return the value of tb_disable_date_vip_permissions.is_view
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Byte getIsView() {
        return isView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.is_view
     *
     * @param isView the value for tb_disable_date_vip_permissions.is_view
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setIsView(Byte isView) {
        this.isView = isView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.likes
     *
     * @return the value of tb_disable_date_vip_permissions.likes
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.likes
     *
     * @param likes the value for tb_disable_date_vip_permissions.likes
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.album_count
     *
     * @return the value of tb_disable_date_vip_permissions.album_count
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Integer getAlbumCount() {
        return albumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.album_count
     *
     * @param albumCount the value for tb_disable_date_vip_permissions.album_count
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setAlbumCount(Integer albumCount) {
        this.albumCount = albumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.diary_pic_count
     *
     * @return the value of tb_disable_date_vip_permissions.diary_pic_count
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Integer getDiaryPicCount() {
        return diaryPicCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.diary_pic_count
     *
     * @param diaryPicCount the value for tb_disable_date_vip_permissions.diary_pic_count
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setDiaryPicCount(Integer diaryPicCount) {
        this.diaryPicCount = diaryPicCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.is_back
     *
     * @return the value of tb_disable_date_vip_permissions.is_back
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Byte getIsBack() {
        return isBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.is_back
     *
     * @param isBack the value for tb_disable_date_vip_permissions.is_back
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setIsBack(Byte isBack) {
        this.isBack = isBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.update_time
     *
     * @return the value of tb_disable_date_vip_permissions.update_time
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.update_time
     *
     * @param updateTime the value for tb_disable_date_vip_permissions.update_time
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_disable_date_vip_permissions.update_admin
     *
     * @return the value of tb_disable_date_vip_permissions.update_admin
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public Integer getUpdateAdmin() {
        return updateAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_disable_date_vip_permissions.update_admin
     *
     * @param updateAdmin the value for tb_disable_date_vip_permissions.update_admin
     *
     * @mbg.generated Tue Aug 02 12:01:33 CST 2022
     */
    public void setUpdateAdmin(Integer updateAdmin) {
        this.updateAdmin = updateAdmin;
    }
}